language: php

sudo: false

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

install:
    - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > ~/.composer/auth.json
    - composer install --prefer-dist


script:
    - php vendor/bin/phpcs --standard=PSR2 View/ Helper/ Test/
    - php vendor/bin/phpmd View/,Helper/,Test/ text cleancode,codesize,controversial,design,naming,unusedcode
    - php vendor/bin/phpcpd View/ Helper/ Test/
    - php vendor/bin/phpunit Test/